/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.BarMenu;

/**
 *
 * @author SnakyDH
 */
public class Help extends javax.swing.JDialog {

    /**
     * Creates new form Helps
     */
    public Help(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblYouCan = new javax.swing.JLabel();
        lbl1Help = new javax.swing.JLabel();
        lbl2Help = new javax.swing.JLabel();
        lbl3Help = new javax.swing.JLabel();
        lbl4Help = new javax.swing.JLabel();
        lbl5Help = new javax.swing.JLabel();
        lblHelpTittle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(106, 126, 252));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblYouCan.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblYouCan.setForeground(new java.awt.Color(255, 255, 255));
        lblYouCan.setText("Give it you can :)");
        jPanel1.add(lblYouCan, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, -1, -1));

        lbl1Help.setBackground(new java.awt.Color(60, 0, 253));
        lbl1Help.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        lbl1Help.setForeground(new java.awt.Color(255, 255, 255));
        lbl1Help.setText("1. You have the purple cards to be able to turn them.");
        jPanel1.add(lbl1Help, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        lbl2Help.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        lbl2Help.setForeground(new java.awt.Color(255, 255, 255));
        lbl2Help.setText(" 2. The Reset button is used to restart the game.");
        jPanel1.add(lbl2Help, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        lbl3Help.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        lbl3Help.setForeground(new java.awt.Color(255, 255, 255));
        lbl3Help.setText("3. The Exit and save button is used to save your score and close the program.");
        jPanel1.add(lbl3Help, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        lbl4Help.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        lbl4Help.setForeground(new java.awt.Color(255, 255, 255));
        lbl4Help.setText("4. In the upper-right corner you can see the UserName you registered.");
        jPanel1.add(lbl4Help, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        lbl5Help.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        lbl5Help.setForeground(new java.awt.Color(255, 255, 255));
        lbl5Help.setText("5. In the upper-left corner you can see the Score you have.");
        jPanel1.add(lbl5Help, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        lblHelpTittle.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblHelpTittle.setForeground(new java.awt.Color(209, 50, 50));
        lblHelpTittle.setText("Help Secction");
        jPanel1.add(lblHelpTittle, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Help.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Help.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Help.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Help.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Help dialog = new Help(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl1Help;
    private javax.swing.JLabel lbl2Help;
    private javax.swing.JLabel lbl3Help;
    private javax.swing.JLabel lbl4Help;
    private javax.swing.JLabel lbl5Help;
    private javax.swing.JLabel lblHelpTittle;
    private javax.swing.JLabel lblYouCan;
    // End of variables declaration//GEN-END:variables
}
